services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
      - ./templates:/etc/nginx/templates
      - ./src/frontend/build:/usr/share/nginx/html:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - streamwatch.api
      
  streamwatch.api:
    container_name: streamwatch.api
    image: streamwatch.api
    build:
      context: .
      dockerfile: src/backend/StreamWatch.Api/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__RedisConnection=redis:6379,abortConnect=false
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
      - JWT__Key=${JWT_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
      - Storage__AccessKey=${STORAGE_ACCESS_KEY}
      - Storage__SecretKey=${STORAGE_SECRET_KEY}
      - Storage__ServiceURL=${STORAGE_SERVICE_URL}
      - Storage__PublicBucket=${STORAGE_PUBLIC_BUCKET}
      - Storage__PublicBaseUrl=${STORAGE_PUBLIC_BASE_URL}
      - Storage__LimitUsagePerUser=${STORAGE_LIMIT}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/MAJOR/docker
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "127.0.0.1:9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
  
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "127.0.0.1:9091:5540"
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis

  seq:
    image: datalust/seq:latest
    ports:
      - "127.0.0.1:5341:80"
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_FIRSTRUN_ADMINPASSWORD}
    volumes:
      - ./seq-data:/data
    restart: unless-stopped

volumes:
  redis_data:
  redis-insight-data:
    driver: local
  postgres-db-volume:
    driver: local