services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
      - ./templates:/etc/nginx/templates
      - ./src/frontend/build:/usr/share/nginx/html:ro
    ports:
      - "433:443"
      - "12345:80"
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80

   
  streamwatch.api:
    image: streamwatch.api
    build:
      context: .
      dockerfile: src/backend/StreamWatch.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=pgdb;Username=postgres;Password=postgres;Trust Server Certificate=true
      - ConnectionStrings__RedisConnection=redis://redis:6379

    
  frontend:
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "4444:80"
    environment:
      NODE_ENV: production


  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/MAJOR/docker
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pgdb
  
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres-db-volume:
    driver: local