services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
      - ./templates:/etc/nginx/templates
      - ./src/frontend/build:/usr/share/nginx/html:ro
    ports:
      - "443:443"
      - "80:80"
    environment:
      - NGINX_HOST=example.com
      - NGINX_PORT=80

   
  streamwatch.api:
    image: streamwatch.api
    build:
      context: .
      dockerfile: src/backend/StreamWatch.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__RedisConnection=redis:6379,abortConnect=false
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
      - JWT__Key=${JWT_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
      - Storage__AccessKey=${STORAGE_ACCESS_KEY}
      - Storage__SecretKey=${STORAGE_SECRET_KEY}
      - Storage__ServiceURL=${STORAGE_SERVICE_URL}
      - Storage__PublicBucket=${STORAGE_PUBLIC_BUCKET}
      - Storage__PublicBaseUrl=${STORAGE_PUBLIC_BASE_URL}
      - Storage__LimitUsagePerUser=${STORAGE_LIMIT}
  

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/MAJOR/docker
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: 1234
      # Optional: Set an initial admin password.
      # SEQ_FIRSTRUN_ADMINPASSWORD: your_strong_password 
      # Or, if you prefer a pre-hashed password:
      # SEQ_FIRSTRUN_ADMINPASSWORDHASH: your_hashed_password_value
    volumes:
      - ./seq-data:/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres-db-volume:
    driver: local